import { Link } from "react-router-dom";
import { Carousel } from "react-responsive-carousel";
import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import "react-responsive-carousel/lib/styles/carousel.min.css";

import photo1 from "../../assets/project_photos/procrastinationfarm/photo1.png";
import photo2 from "../../assets/project_photos/procrastinationfarm/photo2.png";

export default function SecretSantaOrganizer() {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  const handleBackClick = () => {
    navigate("/");

    // Wait for the homepage to load before scrolling to #projects
    setTimeout(() => {
      const el = document.getElementById("projects");
      if (el) el.scrollIntoView({ behavior: "instant" });
    }, 100); 
  };

  return (
    <div className="p-8 pt-25 max-w-4xl mx-auto text-gray-800">
      {/* Back Button */}
      <button
        onClick={handleBackClick}
        className="text-colour1 hover:underline mb-6 inline-block"
      >
        ← Back to Main Page
      </button>

      {/* Title */}
      <h1 className="text-4xl font-bold text-colour1 mb-4">Secret Santa Organizer</h1>

      {/* Carousel */}
      {/* <div className="mb-8 w-full flex justify-center">
        <div className="w-full max-w-2xl">
        <Carousel
          autoPlay
          infiniteLoop
          showThumbs={false}
          showStatus={false}
          className="rounded-xl shadow-md"
        >
          <div>
            <img src={photo1} />
          </div>
          <div>
            <img src={photo2} />
          </div>
        </Carousel>
        </div>
      </div> */}

      {/* Intro Description */}
      <p className="mb-6">
        Welcome to Secret Santa Organizer!
      </p>
      <p className="mb-6">
        Secret Santa Organizer is an automated way to shuffle names for Secret Santa gift exchanges, used by my family for our secret santa draws over the years.
      </p>
      <p className="mb-6">
        The problem was my family has so many old people that they couldn't use an online secret santa generator like Elfster, they simply wanted to be emailed who they had for secret santa. 
      </p>
      <p className="mb-6">
        This is my grade 11 computer science project :) and the project I fell in love with coding with. Thank you to Mr. Knowles my computer science teacher in grade 11 and 12 who gave me a laptop to take home during the pandemic which allowed me to continue this project. 
      </p>
      <p className="mb-6">
        I loved this project so much that every year I have slowly be making it better and better, while also continuoulsy bothering my family by forcing them to use my creation. Even when a simple paper-and-hat Secret Santa draw was much much easier than the process I made them go through. 
      </p>
      <ol className="list-disc list-inside space-y-2">
        <li>The initial project built in grade 11 was not entirely functional but it did have a beautiful ui (this it can be found under the early-work folder in the repo).</li>
        <li>In grade 12 I continued the project and made it functional for the first time. And by functional I mean that we had to sit around a table and pass the computer around to check who had who.</li>
        <li>In my first year of university, I abondened the initial ui so that the app was easier to use, but much of the process was hardcoded.</li>
        <li>In my second year of university, I made the app have restrictions for the first time (i.e. Kaelyn can't buy for Lauren).</li>
        <li>In my third year of undergrad, I figured out how to send emails from a script I wrote!!! (This was huge because before I was sending the emails to everyone manually)</li>
        <li>In my fourth year of undergrad, I made a new ui (this can be found under the later-work folder in the repo). </li>
      </ol>
      <p className="mb-6">
      </p>
      <p className="mb-6">
        I am sure I will keep editing this project around christmas time every year, this is just the latest update for my over-engineered secret santa draw creation, I hope you enjoy! 
      </p>

      {/* How It Works */}
      <h2 className="text-2xl font-semibold text-colour1 mt-10 mb-4">How It Works</h2>
      <ol className="list-decimal list-inside space-y-2">
        <li>Upload a json file to the website containing the names of people in your secret santa draw, their emails, their wishlist, and any restrictions (i.e. Kaelyn can't buy for Lauren).</li>
        <li>Download the json generated by the website and pass it into the email sending script, so that everyone gets emailed who they are supposed to buy a present for!</li>
      </ol>
    </div>
  );
}
